language: java
jdk: oraclejdk8


install: true
script: mvn clean install

dist: trusty
sudo: false

deploy:
  provider: bintray
  api_key: b25b8558a214d7f5d334061c5037fd22c118a8f1
  user: satsa05
 
  
  file: dist.json
  skip_cleanup: true
  on:
    branch: master
    tags: false

