language: java
jdk: oraclejdk8


install: true
script: mvn clean install

dist: trusty
sudo: false

deploy:
  provider: releases
  api_key: ${api_key}
  file: "build/libs/JavaExample.jar"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
