language: java
jdk: oraclejdk8


install: true
script: mvn clean install

dist: trusty
sudo: false

deploy:
  provider: bintray
  api_key: mRnRFK2Aq9ip4B2e7jXu
  user: satsa05
  key: $BINTRAY_API_KEY
  
  file: target/JavaExample.jar
  skip_cleanup: true
  on:
    branch: master
    tags: false
    repo: satsa05/Repository