language: java
jdk: oraclejdk8


install: true
script: mvn clean install

dist: trusty
sudo: false

deploy:
  provider: releases
  api_key: mRnRFK2Aq9ip4B2e7jXu
  file: "build/libs/JavaExample.jar"
  skip_cleanup: false
  on:
    all_branches: false
    tags: true
